serverInfo:
  name: "AcesListenerZen"
  description: "ACES Listener implementation for Zen"
  version: "1.0.0"
  websiteUrl: "https://zensystem.io"

maxScanBlockDepth: 4

zenRpc:
  username: zenrpc
  password: change_this_to_a_long_random_password

server:
  port: 9090

arkAuth:
  requireAuth: false

  # Ark Network to use for fetching and broadcasting ark auth transactions
  arkNetworkConfigPath: "ark_network_config/mainnet.yml"

  # The address that fees are sent to
  serviceArkAddress: "ARNJJruY6RcuYCXcwWsu4bx9kyZtntqeAx"

  # Amount of ARK required in your stake account address
  minArkStake: "0"

  # Amount of ARK to charge payment account every 24 hours to keep
  # API key active
  arkFee: "0"

logging:
  level:
    com.arkaces.aces_listener_zen.ZenEventListener: ERROR
